# SPDX-License-Identifier: AGPL-3.0-only

# This file is part of `idris-ct` Category Theory in Idris library.

# Copyright (C) 2019 Stichting Statebox <https:#statebox.nl>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https:#www.gnu.org/licenses/>.

[package]
name = "statebox/idris-ct"
version = "0.1.0"
authors = []
license = "AGPL-3.0-only"

[targets.lib]
path = "src/"
mods = [ "Basic.Category"
       , "Basic.Functor"
       , "Basic.Isomorphism"
       , "Basic.NaturalIsomorphism"
       , "Basic.NaturalTransformation"
       , "Cats.CatsAsCategory"
       , "Cats.FunctorsAsCategory"
       , "CoLimits.CoCone"
       , "CoLimits.CoConeCat"
       , "CoLimits.CoLimit"
       , "CoLimits.CoLimitAsInitialObject"
       , "CoLimits.CoProduct"
       , "CoLimits.InitialObject"
       , "CoLimits.InitialObjectAsCoLimit"
       , "CommutativeDiagram.Diagram"
       , "Discrete.DiscreteCategory"
       , "Discrete.FunctionAsFunctor"
       , "Dual.DualCategory"
       , "Dual.DualFunctor"
       , "Empty.EmptyCategory"
       , "Empty.EmptyFunctor"
       , "Free.Graph"
       , "Free.Path"
       , "Free.PathCategory"
       , "Free.FreeFunctor"
       , "Idris.EitherAsCoProduct"
       , "Idris.FunctorAsCFunctor"
       , "Idris.TypesAsCategory"
       , "Idris.TypesAsCategoryExtensional"
       , "Monad.Monad"
       , "Monad.KleisliCategory"
       , "Monoid.Monoid"
       , "Monoid.MonoidAsCategory"
       , "Monoid.MonoidMorphism"
       , "Monoid.MonoidMorphismAsFunctor"
       , "Monoid.MonoidsCategory"
       , "MonoidalCategory.MonoidalCategory"
       , "MonoidalCategory.MonoidalCategoryHelpers"
       , "MonoidalCategory.StrictMonoidalCategory"
       , "MonoidalCategory.SymmetricMonoidalCategory"
       , "MonoidalCategory.SymmetricMonoidalCategoryHelpers"
       , "PointedTypes.PointedTypesAsCategory"
       , "Preorder.MonotoneMap"
       , "Preorder.MonotoneMapAsFunctor"
       , "Preorder.PreorderAsCategory"
       , "Preorder.UniquePreorder"
       , "Product.ProductCategory"
       , "Product.ProductFunctor"
       , "CategoryReasoning"
       , "Utils"
       ]
idris_opts = ["-p", "contrib"]
